[project]
name = 'Tokenized-Financial-Regulatory-Sandbox'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.innovation-registration]
path = 'contracts/innovation-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.outcome-assessment]
path = 'contracts/outcome-assessment.clar'
clarity_version = 2
epoch = 2.5

[contracts.participant-verification]
path = 'contracts/participant-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
